---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: launch instance
      amazon.aws.ec2_instance:
        key_name: "ohio"
        aws_access_key: "AKIASUABPVLSEVE2NEFU"
        aws_secret_key: "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"
        security_group: "launch-wizard-1"
        instance_type: "t2.micro"
        image_id: "ami-05f998315cca9bfe3"
        wait: true
        region: "ap-southeast-2"
        count: 1
        tags:
          count_tag: 
          name: "auto" 
          instance_tag:
          name: "auto"
        vpc_subnet_id: "subnet-0811041e8359c1a70"
        network:
          assign_public_ip: yes
      register: ec2

    - debug:
        var: ec2
          # - debug:
          #var: "{{ec2.instances[0].public_ip_address }}"

    
