---
- hosts: all
  become: true
  tasks: 
    - block:
        - name: Install Apache
          apt: name=apache2 state=present

        - name: start apache
          service: name=apache2 state=started
      when: ansible_os_family == "Debian"
      rescue:
        - debug:
            msg: "from rescue block"

      always:
        - debug:
            msg: "from always block"

    - block:
        - name: install httpd
          yum: name=httpd state=present

        - name: start httpd
          service: name=httpd state=started
      when: ansible_os_family == "RedHat"
