---
- hosts: all
  become: true
  tasks:
    - name: Install apache on ubuntu
      apt:
        name: apache2
        state: present

    - name: Starting apache server
      service:
        name: apache2
        state: started
        enabled: true
