---
- hosts: all
  become: true
  tasks:
    - name: change apache port number
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen'
        insertafter: '^#Listen'
        line: Listen 90

    - name: restart apache
      service: 
        name: apache2
        state: restarted

